services:
  agentgateway:
    container_name: agentgateway
    restart: unless-stopped
    image: cr.agentgateway.dev/agentgateway:v1.3.1
    # Replace with your user and group IDs, such as the output of: id -u && id -g
    user: "1000:1000"
    ports:
      - "3000:3000"
      - "4000:4000"
      - "127.0.0.1:15000:15000"
    volumes:
      - ./agentgateway-config:/config
